stages:
  - build
  - test
  - deploy

before_script:
  # add gitlab ssh key (on Linux only)
  - >
    test $(uname -s) != "Darwin" &&
    echo "Setting up Gitlab SSH key" &&
    mkdir -p ~/.ssh &&
    chmod 700 ~/.ssh &&
    echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64 &&
    base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa &&
    chmod 600 ~/.ssh/id_rsa &&
    echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


build:
  stage: build
  image: jimador/docker-jdk-8-maven-node
  tags:
    - build

  artifacts:
    paths:
      - dist
    expire_in: 2 weeks

  variables:
    GIT_STRATEGY: fetch

  script:
    # Build ESP32 Eclipse Plugins
    - echo "Hello Dmitry!"
    - git submodule update --init
    - ls
    - keytool -genkey -dname "cn=Dmitry Yakovlev, ou=SW, o=Espressif Systems Ltd, c=CN" -alias business -keypass key123 -keystore esp32_plugins.key -storepass key123 -validity 360
    - ls
    - mvn clean install 
    - ls com.espressif.esp32.repository
    - ls com.espressif.esp32.repository/target
    #- ls com.espressif.esp32.repository/target/$REL_NAME.zip
    - mkdir -p dist
    - mv com.espressif.esp32.repository/target/*.zip dist/
    #- mv com.espressif.esp32.repository/target/$REL_NAME.zip dist/


    